spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/credit_db}
    username: credit_user
    password: credit_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      initialization-fail-timeout: 0   # ne bloque pas le démarrage sur erreur de connexion initiale, log clairement l'erreur
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080