spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/credit_db}
    username: credit_user
    password: credit_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG  