spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/credit_db
    username: credit_user
    password: credit_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080